name: shokei
description: 推理文字冒险游戏《魔法少女ノ魔女裁判》的二次创作的移动应用
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  audioplayers: ^6.5.1
  vibration: ^3.1.4
  vibration_web: ^1.6.8
  flutter_hooks: ^0.20.5
  url_launcher: ^6.3.1
  package_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.4"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/audio/

flutter_launcher_icons:
  image_path: "assets/images/splash_logo.png"
  web:
    generate: true
    background_color: "#953949"
    theme_color: "#4B0029"
