name: Build iOS IPA (Unsigned)

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 3 1 * *'  # run every month to keep artifacts fresh

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.6'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS app (unsigned)
        run: |
          flutter build ios --release --no-codesign

      - name: Create IPA from app bundle
        run: |
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r shokei-nosign.ipa Payload
          rm -rf Payload

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: shokei-ios-nosign
          path: shokei-nosign.ipa
          retention-days: 60

      - name: Get app version
        id: version
        run: |
          VERSION=$(grep "version:" pubspec.yaml | sed 's/version: //')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Upload build info
        uses: actions/upload-artifact@v4
        with:
          name: build-info
          path: |
            pubspec.yaml
            build/ios/iphoneos/Runner.app/Info.plist
          retention-days: 30
